In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape # 形状是一个Tensor

torch.Size([12])

In [5]:
x.numel() # number of elements 标量

12

In [6]:
x = x.reshape(3, 2, 2)
x

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).shape

torch.Size([3, 4])

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 2, 2))
Y = torch.tensor([[[2.0, 1], [4, 3]], [[1, 2], [3, 4]], [[4, 3], [2, 1]]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1), torch.cat((X, Y), dim=2)

(tensor([[[ 0.,  1.],
          [ 2.,  3.]],
 
         [[ 4.,  5.],
          [ 6.,  7.]],
 
         [[ 8.,  9.],
          [10., 11.]],
 
         [[ 2.,  1.],
          [ 4.,  3.]],
 
         [[ 1.,  2.],
          [ 3.,  4.]],
 
         [[ 4.,  3.],
          [ 2.,  1.]]]),
 tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 2.,  1.],
          [ 4.,  3.]],
 
         [[ 4.,  5.],
          [ 6.,  7.],
          [ 1.,  2.],
          [ 3.,  4.]],
 
         [[ 8.,  9.],
          [10., 11.],
          [ 4.,  3.],
          [ 2.,  1.]]]),
 tensor([[[ 0.,  1.,  2.,  1.],
          [ 2.,  3.,  4.,  3.]],
 
         [[ 4.,  5.,  1.,  2.],
          [ 6.,  7.,  3.,  4.]],
 
         [[ 8.,  9.,  4.,  3.],
          [10., 11.,  2.,  1.]]]))

In [14]:
X == Y

tensor([[[False,  True],
         [False,  True]],

        [[False, False],
         [False, False]],

        [[False, False],
         [False, False]]])

In [15]:
X.sum()

tensor(66.)

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a + b # broadcasting mechanism

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, X[-1], X[1:3] # the last element, the 2nd & 3rd elements

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
X[::2, ::3]

tensor([[ 0.,  3.],
        [ 8., 11.]])

In [20]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [22]:
id(Y)

2725130111488

In [23]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y # 原地操作
print(id(Z))

2725130062848
2725130062848


In [24]:
before = id(X)
X += Y
id(X) == before

True

In [25]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [26]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [27]:
a = torch.arange(12)
b = a.reshape((3, 4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
a.dim()

1